### ISSUE TITLE
Decimated mesh should not be hardcoded

### ISSUE THREAD

**Issue by miguelriemoliveira** [DanielCoelho112/synfeal#83]
```
        #TODO this should not be hardcoded
```

https://github.com/DanielCoelho112/localization_end_to_end/blob/4a1d66dae3de7a10fbd54026c67bb7667140f9be/localbot_core/src/automatic_data_collection.py#L305

**Comment by DanielCoelho112** [comment]
The decimated mesh should be named according to the original mesh. 
Example: santuario_collision.dae is the decimated mesh of santuario.dae. They should also be in the same directory.
![image](https://user-images.githubusercontent.com/73063947/191801605-9f1d2ca5-53ba-41ff-99b8-316e3fc924b5.png)
