### ISSUE TITLE
Time limitations to train all the models 

### ISSUE THREAD

**Issue by andrefdre** [DanielCoelho112/synfeal#98]
Due to time limitations, it's not possible to train 5 models for each case and network. Currently, I only have available 1 GPU in deeplar. What should I do, @miguelriemoliveira?

**Comment by DanielCoelho112** [comment]
As I previously suggested, I think that one run for each case and network is sufficient.  The tables show that there are no significant differences between runs.

**Comment by miguelriemoliveira** [comment]
Right. Let's do 1 run per approach. Later if we have more gpus we can go back to this ...

**Comment by miguelriemoliveira** [comment]
@DanielCoelho112 , can't we give some priority to @andrefdre  since he's close to finishing the thesis?

**Comment by DanielCoelho112** [comment]
> @DanielCoelho112 , can't we give some priority to @andrefdre since he's close to finishing the thesis?

Yes, we can. I'll liberate one GPU by the end of the day.
Still, I think one run is enough. All papers in localization (and in Deep Learning in general) are only trained once. Running 5 runs, would take around 50 experiments, which would take too much time.

**Comment by miguelriemoliveira** [comment]
Right. One is enough. Just i  case he needs it for some other test...

**Comment by andrefdre** [comment]
Thanks, I will then train only one model with 2 GPU I will end the trains faster.
